#! /bin/bash

# ALL GO SCRIPT ALIASES.
alias g='source ~/.vim/scripts/gb.bash'

#short-cut to the commands.
alias c='clear'
alias cg='grep -in --color -I'
alias cgr='grep -in --color -rI'
alias gg='git grep -a -i'
alias ll='ls -l'
alias lt='ls -ltr'
alias h='history  | tail -39 | more'
alias lc='locate'
alias cp='cp -i '
alias mv='mv -i '
alias rm='rm -i'
alias ts='tmux list-session'
alias ta='tmux -2 attach -d '
alias tax='tmux -CC attach -d '
alias tm='TERM=xterm-256color tmux'
alias ft="ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/ /' -e 's/-/|/'"
alias tdmp="sudo tcpdump -nnvvXSes 1500 "
alias plin="git clone -v --depth 1 git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git"
alias t='tree -f -L'
alias url="realpath "
alias ovpn='sudo service  openvpn@client start'
alias sys='tail -f /var/log/syslog'

if [[ "$__PLATFORM__" == 'Linux' ]]; then
    # Ubuntu
    alias log="tail -f /var/log/{messages,kernel,dmesg,syslog}"
    alias agi="sudo apt-get install -y "
    alias ls='ls --color=auto'
    alias lcd='sudo updatedb'
elif [[ "$__PLATFORM__" == 'Darwin' ]]; then
    #MAC
    export CLICOLOR=yes
    alias lcd='sudo /usr/libexec/locate.updatedb'
fi
